-- 그룹별 조건에 맞는 식당 목록 출력하기

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, LEFT(R.REVIEW_DATE, 10) AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS P
ON R.MEMBER_ID=P.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*)=(
        SELECT MAX(A.CNT)
        FROM (
            SELECT COUNT(MEMBER_ID) AS CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS A
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;