-- 5월 식품들의 총매출 조회하기

SELECT A.PRODUCT_ID, B.PRODUCT_NAME, A.TOTAL_AMOUNT * B.PRICE AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE "2022-05%"
    GROUP BY PRODUCT_ID
) AS A
JOIN FOOD_PRODUCT AS B
ON A.PRODUCT_ID=B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC