-- 식품분류별 가장 비싼 식품의 정보 조회하기

SELECT B.CATEGORY, B.PRICE AS MAX_PRICE, B.PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) AS A
JOIN FOOD_PRODUCT AS B
ON A.CATEGORY=B.CATEGORY AND A.PRICE=B.PRICE
WHERE B.CATEGORY IN ("과자", "국", "김치", "식용유")
GROUP BY B.CATEGORY
ORDER BY MAX_PRICE DESC;