-- 즐겨찾기가 가장 많은 식당 정보 출력하기

SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, MAX(FAVORITES) AS MF
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) AS A
JOIN REST_INFO AS B
ON A.FOOD_TYPE=B.FOOD_TYPE
WHERE A.MF=B.FAVORITES
ORDER BY B.FOOD_TYPE DESC