-- 취소되지 않은 진료 예약 조회하기

SELECT PA.APNT_NO, PA.PT_NAME, PA.PT_NO, PA.MCDP_CD, D.DR_NAME, PA.APNT_YMD
FROM (
    SELECT A.APNT_NO, A.PT_NO, A.APNT_YMD, A.MDDR_ID, A.MCDP_CD, P.PT_NAME
    FROM PATIENT AS P
    JOIN (
        SELECT APNT_NO, PT_NO, APNT_YMD, MDDR_ID, MCDP_CD
        FROM APPOINTMENT
        WHERE APNT_YMD LIKE "2022-04-13%" AND APNT_CNCL_YN="N"
    ) AS A
    ON P.PT_NO=A.PT_NO
) AS PA
JOIN DOCTOR as D
ON PA.MDDR_ID=D.DR_ID
ORDER BY PA.APNT_YMD;