-- 과일로 만든 아이스크림 고르기

SELECT A.FLAVOR
FROM FIRST_HALF AS A
RIGHT JOIN (
    SELECT FLAVOR
    FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE="fruit_based"
) AS B
on A.FLAVOR=B.FLAVOR
WHERE A.TOTAL_ORDER > 3000
ORDER BY A.TOTAL_ORDER DESC;