# 오랜 기간 보호한 동물(2)

SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_OUTS AS o
LEFT JOIN ANIMAL_INS AS i
ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE o.DATETIME IS NOT NULL
ORDER BY (o.DATETIME - i.DATETIME) DESC
LIMIT 2;