-- 입양 시각 구하기(2)

WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 AS HOUR FROM HOUR_TABLE WHERE HOUR<23
)

SELECT HOUR_TABLE.HOUR, COUNT(ANIMAL_OUTS.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
RIGHT JOIN HOUR_TABLE
ON HOUR_TABLE.HOUR=HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR